### ISSUE TITLE
publish to https://hex.pm/

### ISSUE THREAD

**Issue by mirceal** [lindenbaum/eipmi#5]
Can we please have this published to hex.pm?
it would enable consuming it through hex and make it very easy to leverage both in erlang and elixir.
thank you.

**Comment by schlagert** [comment]
Hi,

that's a nice idea and I'll see what I can do.

Unfortunately, it's not that easy because, to be able to deploy to hex.pm, eipmi as well as [md2](https://github.com/lindenbaum/md2) must be migrated to rebar3... and we still have some legacy project's using rebar2 internally.

**Comment by schlagert** [comment]
Hi,

we've made it finally. There's now a new release 2.0.0 which can be built with rebar3 as well as rebar (2) and which has been published (along with it's dependency) to [hex.pm](https://hex.pm/packages/eipmi). Have fun!

**Comment by mirceal** [comment]
@schlagert thank you. really appreciate it.
