### ISSUE TITLE
Support for IPMI 2.0

### ISSUE THREAD

**Issue by goldcode88** [lindenbaum/eipmi#7]
Does the current eipmi support 2.0, if it is not supported now, is there any plan support? Thanks!

**Comment by schlagert** [comment]
Unfortunately not, eipmi does not support IPMI v2.0. While having support for v2.0 would definitely be great, we don't have plans to add it in the near future.

**Comment by goldcode88** [comment]
Thank you for your clear answer！
“http://lindenbaum.github.io/eipmi/” can not be accessed.  Is there a feature comparison between eipmi and IPMItool or other similar tools?

**Comment by schlagert** [comment]
Oh, we stopped publishing the projects EDoc long ago an obviously forgot to remove the link.

Unfortunately, I am not aware of such a comparison. IPMItool has more features than eipmi which is written to deeply integrate with mTCA systems. I would recommend the following: If you need the feature set or just make occasional queries use IPMItool (e.g. with os:cmd/1). If you want to (natively) integrate resource constrained, IPMI-capable devices into your Erlang/Elixir service use eipmi.

**Comment by goldcode88** [comment]
I got it. Thank you so much for your suggestion!

**Comment by mattjg908** [comment]
Hi @schlagert , would Lindenbaum GmbH be open to contributors so that we may be able to add 2.0 support? If so, might you be able to provide any high level details about the challenges supporting v2 that were not present in 1.5?

**Comment by schlagert** [comment]
Hi @mattjg908,

yes we're open to contributors (via PRs and of course discussions).

From my point of view, the main challenges (and features) relevant for `eipmi` to support 2.0 would be:
* RMCP+ authentication
* Message encryption
* Serial Over LAN (SOL)

**Comment by mattjg908** [comment]
Hi @schlagert , thanks for the quick response and the information! I'm going to follow up with my team today and bring the three points you mentioned up with them, then I'll circle back here in order to get the discussions started, etc.

**Comment by mattjg908** [comment]
@schlagert, I am going to investigate but thought I'd ask you in case you may have it handy... do you have a current, authoritative (organizing body's published work vs somebody else's hosted set of docs) specification for IPMI?

Again, I'm happy to search but thought you might have it already and that would save me hunting around for one. If not, perfectly fine and I will find it.

**Comment by schlagert** [comment]
The IPMI specification is under authority of Intel. Afaik, they also host the official documents, e.g.
https://www.intel.com/content/www/us/en/products/docs/servers/ipmi/ipmi-second-gen-interface-spec-v2-rev1-1.html

**Comment by mattjg908** [comment]
Thanks @schlagert !
